### ISSUE TITLE
pythons > 3.7?

### ISSUE THREAD

**Issue by mgrosso** [xlang-ai/instructor-embedding#100]
Hi!
The Installation section of the README seems to suggest that python 3.7 is needed:

```
conda env create -n instructor python=3.7
```

That seems dubious though. Can you please share which versions of python are supported, or known to work, or even just thought likely to work?

Apologies if I missed someplace that this was already documented. 
Thanks!

**Comment by hongjin-su** [comment]
Hi, Thanks a lot for your interest in the INSTRUCTOR!

The python version should not be very strict. In my later experiments, I also find python 3.10 works well. As sentence-transformers recommend python>=3.6, I suspect that INSTRUCTOR also works with python>=3.6.

Hope this helps!

**Comment by mgrosso** [comment]
thank so much! I'll try bumping to 3.10 and maybe 3.12 afterwards.
