### ISSUE TITLE
No matching distribution found for instructor

### ISSUE THREAD

**Issue by xfzhang990** [xlang-ai/instructor-embedding#104]
I tried to install instructor using
"pip install instructor"
It resulted in error as following: 
ERROR: Ignored the following versions that require a different python version: 0.2.1 Requires-Python >=3.9,<4.0; 0.2.11 Requires-Python >=3.9,<4.0; 0.2.4 Requires-Python >=3.9,<4.0; 0.2.5 Requires-Python >=3.9,<4.0; 0.2.6 Requires-Python >=3.9,<4.0; 0.2.7 Requires-Python >=3.9,<4.0; 0.2.8 Requires-Python >=3.9,<4.0; 0.2.9 Requires-Python >=3.9,<4.0; 0.3.0 Requires-Python >=3.9,<4.0; 0.3.1 Requires-Python >=3.9,<4.0; 0.3.2 Requires-Python >=3.9,<4.0; 0.3.3 Requires-Python >=3.9,<4.0; 0.3.4 Requires-Python >=3.9,<4.0; 0.3.5 Requires-Python >=3.9,<4.0; 0.4.0 Requires-Python >=3.9,<4.0; 0.4.2 Requires-Python >=3.9,<4.0; 0.4.3 Requires-Python >=3.9,<4.0; 0.4.4 Requires-Python >=3.9,<4.0; 0.4.5 Requires-Python >=3.9,<4.0; 0.4.6 Requires-Python >=3.9,<4.0
ERROR: Could not find a version that satisfies the requirement instructor (from versions: none)
ERROR: No matching distribution found for instructor

I have double checked my Python version, it's 3.11.7

Does anyone know why it resulted in above error?

**Comment by Paul-Lukasiewicz** [comment]
Hey ! can you tell us how you fix this please ?
