### ISSUE TITLE
Are document instructions not used for evaluation?

### ISSUE THREAD

**Issue by orionw** [xlang-ai/instructor-embedding#111]
Hi there!  Thanks for the great work!

I was trying to reproduce the MTEB evaluation and noticed that it seems like the instructions for documents are not used.  Is that correct?

See: https://github.com/xlang-ai/instructor-embedding/blob/e749023b14d36cdff234398de57d9b6c519e776a/evaluation/MTEB/mteb/abstasks/AbsTaskRetrieval.py#L738 referencing `sentences` instead of `new_sentences` that contain the instructions.

Totally fine, if that is true (even if unintentional - just trying to reproduce it).

**Comment by hongjin-su** [comment]
Thanks for pointing out! See [here](https://github.com/xlang-ai/instructor-embedding/blob/main/evaluation/MTEB/mteb/abstasks/AbsTaskRetrieval.py#L736) for the latest version!

**Comment by orionw** [comment]
Ah nice, I see it was updated! Sorry, I had started using this repo before then and didn’t realize there had been a change.

Appreciate your time!
