### ISSUE TITLE
Traceback (most recent call last):   File "/home/instructor-embedding/evaluation/prompt_retrieval/main_civil.py", line 15, in <module>     from InstructorEmbedding import INSTRUCTOR ImportError: cannot import name 'INSTRUCTOR' from 'InstructorEmbedding' (/home/instructor-embedding/InstructorEmbedding/__init__.py)

### ISSUE THREAD

**Issue by EricPaul03** [xlang-ai/instructor-embedding#116]
Traceback (most recent call last):
  File "/home/rnd/wmj/instructor-large/instructor-embedding/evaluation/prompt_retrieval/main_civil.py", line 15, in <module>
    from InstructorEmbedding import INSTRUCTOR
ImportError: cannot import name 'INSTRUCTOR' from 'InstructorEmbedding' (/home/instructor-embedding/InstructorEmbedding/__init__.py)
A very simple question, I want to know if there was an error in my installation? I did not find the INSTRUCTOR method in the InstructorEmbedding library, so I reported an error. How should I solve it?

**Comment by 1Fleeting-time** [comment]
cannot import name 'Instructor' from 'InstructorEmbedding'
我现在也遇到了这个问题，请问你解决了吗
