### ISSUE TITLE
domain adaptation method using GPL on instructor

### ISSUE THREAD

**Issue by iavinas** [xlang-ai/instructor-embedding#62]
Hi, I was wondering if we can tune instructor using the GPL method? Link to the repo https://github.com/UKPLab/gpl .

Thanks!

**Comment by hongjin-su** [comment]
Hi, as the GPL can be initialized from a sentence transformer model, it should be OK to further tune INSTRUCTOR with GPL.

**Comment by iavinas** [comment]
got it, thanks for helping @hongjin-su

**Comment by hongjin-su** [comment]
Feel free to re-open the issue if you have any further questions or comments!
