### ISSUE TITLE
What if instruction+text merged?

### ISSUE THREAD

**Issue by takiholadi** [xlang-ai/instructor-embedding#63]
Is it possible to apply somehow for instruction prompts without instruction/text separation?

**Comment by hongjin-su** [comment]
Hi, Thanks a lot for your interest in the INSTRUCTOR!

It is possible to merge the instruction and text as one sentence, and put all the contents in the text body, leaving the instruction as an empty string, but this may be misaligned with the training format.

**Comment by hongjin-su** [comment]
Feel free to re-open the issue if you have any further questions or comments!
