### ISSUE TITLE
Is it ok to train directly using the T5 model as a base? Are the results guaranteed?

### ISSUE THREAD

**Issue by ScottishFold007** [xlang-ai/instructor-embedding#68]
Is it ok to train directly using the T5 model as a base? Are the results guaranteed?

**Comment by hongjin-su** [comment]
Hi, Thanks a lot for your interests in the INSTRUCTOR!

In the training, we initialize the model with GTR, which is a model with T5 architecture, thus, the T5 model should be compatible with the training. However, as T5 is a general sequence-to-sequence model, the results may not be guaranteed.

**Comment by hongjin-su** [comment]
Feel free to re-open the issue if you have any further questions or comments!
