### ISSUE TITLE
Pip install does not include dependencies

### ISSUE THREAD

**Issue by dstengle** [xlang-ai/instructor-embedding#70]
The current package on pypi does not include dependencies, making the package somewhat difficult to use when integrating into other projects rather than just using it on its own.

**Comment by hongjin-su** [comment]
Hi, Thanks a lot for your interest in the INSTRUCTOR!

We separate the InstructorEmbedding from the dependencies, so it will not affect other packages in the existing environment. To install the dependencies, you may simply run the following pip command:
```bash
pip install -r requirements.txt
```

**Comment by hongjin-su** [comment]
Feel free to re-open the issue if you have any further questions or comments!
