### ISSUE TITLE
what is the max input size?

### ISSUE THREAD

**Issue by vyau** [xlang-ai/instructor-embedding#72]
Hi Instructor team:   When I feed content into instructor to generate embedding,
I saw this in stdout:

   max_seq_length  512

I assume that means there is some input cap at 512 bytes?
What happen if I my input is larger than that size?
thanks

**Comment by hongjin-su** [comment]
Hi, Thanks a lot for your interest in the INSTRUCTOR!

The input text will be truncated if the length is larger than 512.

**Comment by amitduwal** [comment]
@hongjin-su 
Does that mean if chunks of 1000 tokens are passed to the embedding model the remaining 488 tokens are lost?
and how would you generate the embeddings for a log text or document with multiple pages?

**Comment by hynky1999** [comment]
See here https://github.com/HKUNLP/instructor-embedding/blob/main/InstructorEmbedding/instructor.py#L321.
You can then look into tokenizers docs and find out that any token over 512 is scraped.

**Comment by hynky1999** [comment]
Also the unit used for sequence length is TOKEN not byte or character.

**Comment by dassaswat** [comment]
So I am trying to push embeddings to a vector and before even encoding documents using instructor I want to chuck the documents to something less than 512 tokens. How do I do it?

**Comment by hongjin-su** [comment]
Thanks a lot for the reply! @hynky1999 
Feel free to re-open the issue if you have any further questions or comments!
