### ISSUE TITLE
Kernel dies when calling HuggingFaceInstructEmbedding

### ISSUE THREAD

**Issue by lavalosan** [xlang-ai/instructor-embedding#73]
Hi, I am trying to execute this cell on a Jupiter notebook (python 3.9.16) 

`from langchain.embeddings import HuggingFaceInstructEmbeddings
from tqdm import tqdm

instructor_embeddings = HuggingFaceInstructEmbeddings(model_name = "hkunlp/instructor-xl", model_kwargs = {"device" : "cpu"})`

at first the cell produces : 

load INSTRUCTOR_Transformer

then after a few seconds :

**Cannot execute code, session has been disposed. Please try restarting the Kernel.
The Kernel crashed while executing code in the the current cell or a previous cell. Please review the code in the cell(s) to identify a possible cause of the failure.**

Do you know what could be the cause of this Jupyter error ?

**Comment by hongjin-su** [comment]
Is it because there is not enough memory for the model?

**Comment by hongjin-su** [comment]
Feel free to re-open the issue if you have any further questions or comments!
