### ISSUE TITLE
Instruction for keywords retrievial 

### ISSUE THREAD

**Issue by Bobolx00** [xlang-ai/instructor-embedding#90]
hi!
I'm currently using the instructor-xl model, using as query a phrases to retrieve relevant keyword. 
I noticed that if I apply an instruction, the performance degradate (may be because I'm the training set, the query instruction usually introduce a string that is shorter than the string introduced with the document - passages instruction)

Any suggestions for instructions pair?

Thanks in advance!

**Comment by hongjin-su** [comment]
Hi, Thanks a lot for your interest in the INSTRUCTOR!

You may try to follow the instruction template: `Represent {domain} {text_type} for {task_objective}:`. For example, if the query is a news article, and we use it to retrieve relevant keywords, we may write instructions like `{'query': 'Represent a news article for retrieving relevant keywords:', 'document': 'Represent a keyword for retrieval:'}`

Hope this helps!

**Comment by hongjin-su** [comment]
Feel free to re-open the issue if you have any questions or comments!
