### ISSUE TITLE
How would you use instructor o find duplicate items in similar texts, e.g short bug descriptions?

### ISSUE THREAD

**Issue by shgidi** [xlang-ai/instructor-embedding#95]

**Comment by hongjin-su** [comment]
Hi, Thanks a lot for your interest in the INSTRUCTOR!

Probably you may try `Represent the code error description for retrieval` or `Represent the code error sentence`

**Comment by hongjin-su** [comment]
Feel free to re-open the issue if you have any questions or comments!
